### PR TITLE
fix: cron should still execute after changing the time back during daylight savings

### LINKED ISSUE #881: Missing Cron Execution during DST change
### Description

Hi, thanks to author and everyone contributing for making this amazing library possible.

Encountered an issue where the cron jobs aren't triggering during daylight saving change.

For example: TimeZone - Australia/Melbourne 7 Apr 2024 - Daylight savings time ended and clocks turned back 1 hour
Time goes from 2:59 -> 2:00 (See example below)

### Expected Behavior

The Cron job should trigger every half an hour (See example below)

### Actual Behavior

The Cron job didn't trigger for one hour and missed two executions. Missing `cron job executed` log two times (See example below)

### Steps to Reproduce

```
const { CronJob } = require("cron");
const fakeTImers = require("@sinonjs/fake-timers");

process.env.TZ = "Australia/Melbourne";

const main = () => {
  const clock = fakeTImers.install({
    now: new Date("2024-04-07T01:00:00.000"),
  });
  const job = new CronJob(
    "*/30 * * * *", // every 30 minutes
    function () {
      console.log(
        "Cron job executed. The current time is: ",
        new Date().toString()
      );
    },
    null,
    true,
    "Australia/Melbourne"
  );

  console.log("current time is: ", new Date().toString());
  console.log("Going to advance time by 30 minutes");
  clock.tick(1000 * 60 * 30);
  console.log("Time after advancing is ", new Date().toString());
  console.log("\n");

  console.log("current time is: ", new Date().toString());
  console.log("Going to advance time by 30 minutes");
  clock.tick(1000 * 60 * 30);
  console.log("Time after advancing is ", new Date().toString());
  console.log("\n");

  console.log("current time is: ", new Date().toString());
  console.log("Going to advance time by 30 minutes");
  clock.tick(1000 * 60 * 30);
  console.log("Time after advancing is ", new Date().toString());
  console.log("\n");

  console.log("current time is: ", new Date().toString());
  console.log("Going to advance time by 30 minutes");
  clock.tick(1000 * 60 * 30);
  console.log("Time after advancing is ", new Date().toString());
  console.log("\n");

  console.log("current time is: ", new Date().toString());
  console.log("Going to advance time by 30 minutes");
  clock.tick(1000 * 60 * 30);
  console.log("Time after advancing is ", new Date().toString());
  console.log("\n");

  console.log("current time is: ", new Date().toString());
  console.log("Going to advance time by 30 minutes");
  clock.tick(1000 * 60 * 30);
  console.log("Time after advancing is ", new Date().toString());
  console.log("\n");

  console.log("current time is: ", new Date().toString());
  console.log("Going to advance time by 30 minutes");
  clock.tick(1000 * 60 * 30);
  console.log("Time after advancing is ", new Date().toString());
  console.log("\n");
};

main();
```

Output:

```
current time is:  Sun Apr 07 2024 01:00:00 GMT+1100 (Australian Eastern Daylight Time)
Going to advance time by 30 minutes
Cron job executed. The current time is:  Sun Apr 07 2024 01:30:00 GMT+1100 (Australian Eastern Daylight Time)
Time after advancing is  Sun Apr 07 2024 01:30:00 GMT+1100 (Australian Eastern Daylight Time)


current time is:  Sun Apr 07 2024 01:30:00 GMT+1100 (Australian Eastern Daylight Time)
Going to advance time by 30 minutes
Cron job executed. The current time is:  Sun Apr 07 2024 02:00:00 GMT+1100 (Australian Eastern Daylight Time)
Time after advancing is  Sun Apr 07 2024 02:00:00 GMT+1100 (Australian Eastern Daylight Time)


current time is:  Sun Apr 07 2024 02:00:00 GMT+1100 (Australian Eastern Daylight Time)
Going to advance time by 30 minutes
Cron job executed. The current time is:  Sun Apr 07 2024 02:30:00 GMT+1100 (Australian Eastern Daylight Time)
Time after advancing is  Sun Apr 07 2024 02:30:00 GMT+1100 (Australian Eastern Daylight Time)


current time is:  Sun Apr 07 2024 02:30:00 GMT+1100 (Australian Eastern Daylight Time)
Going to advance time by 30 minutes
Time after advancing is  Sun Apr 07 2024 02:00:00 GMT+1000 (Australian Eastern Standard Time)


current time is:  Sun Apr 07 2024 02:00:00 GMT+1000 (Australian Eastern Standard Time)
Going to advance time by 30 minutes
Time after advancing is  Sun Apr 07 2024 02:30:00 GMT+1000 (Australian Eastern Standard Time)


current time is:  Sun Apr 07 2024 02:30:00 GMT+1000 (Australian Eastern Standard Time)
Going to advance time by 30 minutes
Cron job executed. The current time is:  Sun Apr 07 2024 03:00:00 GMT+1000 (Australian Eastern Standard Time)
Time after advancing is  Sun Apr 07 2024 03:00:00 GMT+1000 (Australian Eastern Standard Time)


current time is:  Sun Apr 07 2024 03:00:00 GMT+1000 (Australian Eastern Standard Time)
Going to advance time by 30 minutes
Cron job executed. The current time is:  Sun Apr 07 2024 03:30:00 GMT+1000 (Australian Eastern Standard Time)
Time after advancing is  Sun Apr 07 2024 03:30:00 GMT+1000 (Australian Eastern Standard Time)


```

### Your Environment

- **`cron` version**: 3.1.7
- **NodeJS version**: 14.17.6
- **Operating System and version**: Ubuntu 16.04
- **TypeScript version (if applicable)**:
- **Link to your project (if applicable)**:

Might be related to: #563  #638

### PR DESCRIPTION
**Pull request by intcreator**
## Description

This PR will fix the issue where cron did not execute after changing the time back during daylight savings. It also replaces `ts-jest` with `@swc/jest` which is a little faster at running tests.

## Related Issue

fixes #881

## Motivation and Context

I ended up doing a big refactor to fix this issue because everything to do with time zones seemed too complicated to understand as is. I decided that rather than trying to decide based on what the time "should" be after a change compared to what it actually was from Luxon, we should just check if the UTC offset changed. That would indicate a daylight savings jump with very little work on our part. Then we could just check if a cron execution was supposed to happen in the gap we skipped.

Building on that idea, I decided to ultimately create a new fake cron time in UTC based on the timezoned time, do all the manipulations without worrying about time zones, and then convert back into the timezoned time and figure out any adjustments if needed.

As for #881 specifically, it looks like some of our date creations were ambiguous. According to the Luxon docs, [you can sometimes create ambiguous times](https://moment.github.io/luxon/#/zones?id=dst-weirdness) if you try to initialize a `DateTime` object in the middle of a daylight savings jumping back event. if the time jumps back and hour at 3 am and I create a `DateTime` at 2:30 am on that day, is it the first 2:30 am or the second 2:30 am? I switched some of our `DateTime` creations to UTC to make the time they represented unambiguous, and I added some checks to see if the previous hour was ambiguous or not before returning the time.

## How Has This Been Tested?

Added a new test case, made sure previous test cases passed (and edited some to make them more clear as to the times being tested), and removed some test cases that tested functions I removed that we no longer needed.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [ ] If my change introduces a breaking change, I have added a `!` after the type/scope in the title (see the Conventional Commits standard).

### CODE REVIEW

File: src/time.ts [hunk 1]
```diff
@@ -259,13 +253,19 @@ export class CronTime {
...
-					if (isDone) break;
+				if (offset !== date.offset) {
+					offset = date.offset;
+					if (
+						date.hour - preDayChangeDate.hour > 1 ||
+						(date.hour === 1 && preDayChangeDate.hour === 23)
+					) {
+						// We skipped past a valid execution time and must execute immediately
+						break;
+					}
```
Comment (sheerlox) [inline src/time.ts:268]: Why is the second check necessary? Wouldn't an offset change always mean a DST forward jump?

Also, maybe add back a `_forwardDSTJump` with a signature like `(preChangeDate: DateTime, date: DateTime, minutes?: boolean): boolean` to avoid duplication?

File: tests/crontime.test.ts [hunk 2]
```diff
@@ -451,7 +451,18 @@ describe('crontime', () => {
...
+		// Europe/Paris DST starts at 30 Mar 2025, 02:00 (+1 to hours)
+		let currentDate = DateTime.fromISO('2025-03-30T01:59', {
+			zone: 'Europe/Paris'
+		});
+		const cronTime = new CronTime('20 4 * * *');
+		const nextDate = cronTime.getNextDateFrom(currentDate, 'Europe/Paris');
+		expect(nextDate.toString()).toEqual(
+			DateTime.fromISO('2025-03-30T04:20', { zone: 'Europe/Paris' }).toString()
+		);
+	});
```
Comment (sheerlox) [inline tests/crontime.test.ts:464]: While reviewing the PR, I had a hunch that because we are not verifying whether an execution was missed and returning the correct execution time like the previous `_forwardDSTJump` did, we would always end up executing when a jump happens, even though no execution is planned during the jump.

I've added a test case to verify this thought, and this is indeed happening:

image

Comment (sheerlox) [reply tests/crontime.test.ts:464]: I have cherry-picked it on the main branch for confirmation, and it doesn't happen there.

File: src/time.ts (hunk 1 above)
Comment (sheerlox) [reply src/time.ts:268]: Not saying it isn't necessary per say, just that I can't seem to wrap my head around it and would like to understand haha

File: tests/crontime.test.ts (hunk 2 above)
Comment (intcreator) [reply tests/crontime.test.ts:464]: yeah I think I might have been too aggressive removing that function. I was just so excited to detect a jump by checking if `offset` changed. I might add it back or a similar helper function that still uses offset to track down the exact time that the change happens

Comment (intcreator) [reply tests/crontime.test.ts]: fixed so your test case passes now! thanks for adding that

File: src/time.ts (hunk 1 above)
Comment (intcreator) [reply src/time.ts]: resolving as outdated; I went with a different method here

**Comment by intcreator** [comment]
I added a couple of custom types to get around a weird issue where Definitely Typed didn't provide all the subproperties on the `Zone` object that I needed. should those definitions go in one of the type files? they're only used in time.ts for now...

**Review by sheerlox — APPROVED** [review]
lgtm, great work!

**Review by sheerlox — DISMISSED** [review]
lgtm, great work!
